module.exports = {
  'Login Page': '/login',
  'PA Request Button': '[href*="/pa-requests"] button',
  'PA Request Page': '.login-block button[type=button]',
  'PA Request Link': '/noauth#/pa-requests',
  'PA Submit Button': '#login-btn',
  'Type of Request': '.select-button',
  'Dialog Modal': '.modal-body',
  'Public Trade Request Form': '#trade-requests',
  'Send Request': '//button[contains(text(),"Send Request")]',
  'Name of Security': '//label[contains(.,"Name of Security")]/../div/input',
  'Ticker Symbol': '//label[contains(.,"Ticker Symbol or Stock Code")]/../input',
  'Exchange': '//label[contains(.,"Exchange")]/../input',
  'Quantity': '//label[contains(.,"Quantity")]/../input',
  'Investment Class': '//label[contains(.,"Investment Class")]/../div',
  email: '.login-block:nth-of-type(1) input',
  password: '.login-block:nth-of-type(2) input',
  nameOfBroker: '.trade-two-column.space-between:nth-of-type(2) div:nth-child(1) input',
  emailOfBroker: '.trade-two-column.space-between:nth-of-type(2) div:nth-child(2) input',
  address: '#discretionary-account div:nth-of-type(3) textarea',
  description: '#discretionary-account div:nth-of-type(4) textarea',
  type: '#discretionary-account div:nth-of-type(5) textarea',
  fileUpload: '#discretionary-account div:nth-of-type(6) input'
}